### PR TITLE
Thanos Map Snap

### PR DESCRIPTION
**Pull request by ben10083-zz**
[Changelogs]: # Removed irrelevant Map files
:cl: 
server: Irrelevant maps have been removed.
/:cl:

[why]: # Reduced clutter of DM, and allowing the important maps to be easier to find.

Went over what to delete with @Kmc2000

### CODE REVIEW

**Review by alexkar598 — CHANGES_REQUESTED** [review]
_maps/_basemap.dm and code/_compile_options.dm needs changing to remove the maps

**Comment by ben10083-zz** [comment]
> _maps/_basemap.dm and code/_compile_options.dm needs changing to remove the maps

Fixed basemap, but I do not see what I need to change in compile options

**Comment by alexkar598** [comment]
LOWMEMORYMODE attempts to load runtimestation

**Comment by ben10083-zz** [comment]
> LOWMEMORYMODE attempts to load runtimestation

Gotcha, changed to Akira

**Comment by alexkar598** [comment]
I still think runtimestation should be left in as it is a debug station used when you don't want to load a main big map

**Comment by ben10083-zz** [comment]
> I still think runtimestation should be left in as it is a debug station used when you don't want to load a main big map

Changed again to Box Station, runtime station no longer exists.

**Comment by alexkar598** [comment]
Boxstation isn't really that better for a debug map...

**Comment by ben10083-zz** [comment]
Need to close for some probing, will reopen a replacement

**Pull request closed without merging**
