### PR TITLE
AI Armor Project

### PR DESCRIPTION
**Pull request by SergeiKoralev**
Incoming Message from Fleet Command: All ships effective immediately. Engineering refit teams have been dispatched to your ships to retrofit them with upgraded security in the vicinity of the Computer cores. All crews are to comply with construction of the new reinforced structures to the best of their ability. Failure to comply will be punished by courts martial.

[Changelogs]: Below is what I did... all changes apply to the Intrepid AND Sovereign.
-Changed out walls so they are reinforced walls
-Extends atmospherics into the AI upload/core rooms.
-Adds AI foam slippers to AI Upload and core rooms.
-Changes out doors with high security doors re-sprited to look like the old ones.

[why]: # Because AIs on the ships are too easy to subvert if you vaguely know what you're doing as an antag. They are high security areas, and yet have effectively little more defense than hydroponics.

### CODE REVIEW

**Review by alexkar598 — DISMISSED** [review]
Will the doors have the correct sprites for the disassembly steps?

**Comment by SergeiKoralev** [comment]
> Will the doors have the correct sprites for the disassembly steps?

They will have default sprites for disassembly because their Icon var is what I changed to get the right sprites. I'll change them back if KMC sprites stages for a proper trek reinforced door. @alexkar598

**Review by Harry-Jubilee — DISMISSED** [review]
Looks good, glad the AI is getting a core upgrade.

👍

**Comment by alexkar598** [comment]
I'm putting reviewing map prs a bit on hold until I can get a system to properly parse the differences in map files.

**Comment by alexkar598** [comment]
By the way im still worried about the AI defenses being unsufficent as its one thermited wall away from death.

**Comment by Kmc2000** [comment]
Theyll always be insufficient as long as the transporter exists

**Comment by SergeiKoralev** [comment]
> By the way im still worried about the AI defenses being unsufficent as its one thermited wall away from death.



> Theyll always be insufficient as long as the transporter exists

Part the first: A reinforced wall is harder to termite if I recall correctly. Even if it isn't, that adds the step of breaking into chemistry to the process rather than grab a welder and a wrench.

Part the second: Transporters are always going to be that way unless I turn the AI core into a shock-grilled fortress and remove the spare IDs from the map so NOBODY can get access changes without mugging the XO or captain directly. Personally I think requiring someone to get SECURITY access in order to use the transporter to bypass a door is enough of a hindrance. It's never going to be perfect, but it sure as hell is better than it was. "Just because" is not an excuse. Even in trek areas like the computer core would have elevated defenses against direct physical entry.

**Comment by Kmc2000** [comment]
I think it's a good change.
A good computer will transporter themselves out of dodge long before they get there

**Review by Kmc2000 — APPROVED** [review]
Cool and good

**Pull request merged**
