### PR TITLE
New Jackets

### PR DESCRIPTION
**Pull request by ben10083-zz**
[Changelogs]: New Jackets for departments.

:cl: ben10083
add: New command jacket
add: New engsec jacket
add: New medsci jacket
tweak: People now spawn with corresponding jacket
/:cl:

[why]: # This will allow people to tell what department each person is in at a glance.

WIP

### CODE REVIEW

**Comment by alexkar598** [comment]
Was this tested in game?

**Comment by ben10083-zz** [comment]
WIP, sprites show up but having trouble with spawning

**Comment by alexkar598** [comment]
Is this still active?

**Comment by Kmc2000** [comment]
Yes

**Review by Kmc2000 — APPROVED** [review]

**Pull request merged**
