### PR TITLE
Tweak the frequency of random events so they're less destructive.

### PR DESCRIPTION
**Pull request by Kmc2000**
:cl: Satan
add: Random events like spontaneous cancer are now less common
/:cl:

### CODE REVIEW

**Review by soryy708 — DISMISSED** [review]

**Review by francinum — CHANGES_REQUESTED** [review]
Just fuck with the weights instead of sandbagging the whole subsystem.

**Review by Jalleo — DISMISSED** [review]

**Review by francinum — CHANGES_REQUESTED** [review]
I reiterate. Adjust specific events. **DO NOT BLANKET SANDBAG THE ENTIRE EVENTS SUBSYSTEM**

**Comment by alexkar598** [comment]
@kmc2000 update on this?

**Comment by alexkar598** [comment]
@Kmc2000 closing this in 5 days if no reply

**Comment by alexkar598** [comment]
Closed for inactivity

**Pull request closed without merging**
