### PR TITLE
Defiant

### PR DESCRIPTION
**Pull request by WorldofLoina**
Adds the skeleton of the Defiant! a new low pop ship, designed as a weapon against the borg by Bejamin Sisko, it later became his pimphand against the Dominion.

Current version has 2 seperate Z levels, missing, wiring and code.

Top Deck

Mid Deck

Bottom Deck

### CODE REVIEW

**Comment by WorldofLoina** [comment]
Added pictures of most recent build of the map

**Comment by Kmc2000** [comment]
It's taking shape 👌
My main gripe is the asymmetry. There are weird bits that stick out in the wrong way and you need to fix that. This is for the general shape of the hull though.

**Comment by WorldofLoina** [comment]
> 
> 
> It's taking shape ok_hand
> My main gripe is the asymmetry. There are weird bits that stick out in the wrong way and you need to fix that. This is for the general shape of the hull though.
https://starmadedock.net/attachments/top-front-jpeg.12785/

It's a symptom of the defiants design when converted to blocks, I can extend the outward parts, bringing more things from Deck 2 onto Deck 1 but not all, largely making Deck 2 less useful then it is now.

That's the big gripe of it's shape atm

**Comment by WorldofLoina** [comment]
https://imgur.com/a/KZrY8x7

Latest itteration of the Defiant, will push to the PR once I've rebuilt the atmos... from the ground up... I don't like atmos.

**Comment by WorldofLoina** [comment]
https://imgur.com/a/j0lWVI3 SCREENSHOTS

**Comment by WorldofLoina** [comment]
Latest Screenshots of build release on the 18th

https://imgur.com/a/6V2gsv6

**Comment by francinum** [comment]
No access portal to the Gravity Generator.

**Comment by alexkar598** [comment]
Closed for inactivity

**Pull request closed without merging**
