### PR TITLE
Adds the PALADIN law board to AI Uploads

### PR DESCRIPTION
**Pull request by Shadow-Quill**
:cl:
add: Adds PALADIN board to the Akira/Sovereign ships.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
We start off with Paladin lawset, so why not.

### CODE REVIEW

**Comment by Shadow-Quill** [comment]
Map merge hates me.
It always does.

**Comment by Shadow-Quill** [comment]
I was mapmerging the wrong maps.
fml

**Review by GoatMonarch — APPROVED** [review]
Just one minor fix I had on my todo list now done by someone else. I'd usualy complain about the board not being pixel-moved but given this is DS13 nothing else is pixel moved so I won't be too much an arse about it.

**Review by Kmc2000 — APPROVED** [review]
Cheers

**Pull request merged**
