### PR TITLE
Adds homestuck troll horns as head accessory and squidwards

### PR DESCRIPTION
**Pull request by Wilchenx**

### CODE REVIEW

**Review by Kmc2000 — DISMISSED** [review]
I was promised a squidward race but instead I got this. Isn't even modularized.

**Comment by alexkar598** [comment]
Improve dont remove kmc

**Comment by Kmc2000** [comment]
I WILL NOT HAVE GOOFBALLS ON MY CODEBASE

**Comment by francinum** [comment]
@Wilchenx I have done no such thing.

**Comment by Wilchenx** [comment]
@francinum technically you did but it was ages ago

**Review by francinum — DISMISSED** [review]

**Comment by Kmc2000** [comment]
Sprite PR with no pictures

**Comment by francinum** [comment]
@Wilchenx Atomize your PR.

**Comment by Wilchenx** [comment]
@francinum get back in your host-cage

**Comment by Kmc2000** [comment]
I want the squidwards, but I don't want the troll horns

Such a dilemma!

**Comment by alexkar598** [comment]
April's fools is over,closing in 24h unless KMC changed his mind about this pr.

**Comment by Wilchenx** [comment]
image

**Comment by Wilchenx** [comment]
i'm gonna sprinkle pickle juice in your eyes and waterboard you with saurkraut water

**Comment by francinum** [comment]
*implies soft power through testmerge*

**Pull request closed without merging**
